# Generated by Django 4.2 on 2023-04-26 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Partners_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('project_year', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=400)),
                ('website', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('type', models.CharField(choices=[('GOV', 'Government'), ('COM', 'For Profit Company'), ('FREE', 'Not For Profit')], max_length=30)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('ACT', 'Active Industry Member'), ('INACT', 'No Longer an Partner')], default='ACT', max_length=30)),
                ('notes', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
