# Generated by Django 4.1.5 on 2023-02-08 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('field', models.CharField(choices=[('ELEC', 'Electrical Engineering'), ('COMP', 'Computer Engineering'), ('SOFT', 'Software Engineering'), ('CIVL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering'), ('SPAC', 'Space Engineering'), ('GEOM', 'Geomatics Engineering'), ('OTHR', 'Other Field')], max_length=30)),
                ('type', models.CharField(choices=[('COMP', 'Competition'), ('LOOSE', 'Loosely Defined'), ('WELLDF', 'Well Defined'), ('C4', 'C4')], max_length=30)),
                ('students', models.CharField(blank=True, default=None, max_length=120)),
                ('supervisor', models.CharField(blank=True, default=None, max_length=60)),
                ('date_proposed', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('PROP', 'Proposed but unstarted'), ('START', 'Started / In Progress'), ('COMPL', 'Completed'), ('EXT', 'Completed but Extendable')], default='PROP', max_length=30)),
                ('date_complete', models.DateField(blank=True, default=None, null=True)),
                ('industry_partners', models.CharField(blank=True, default=None, max_length=60)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
