# Generated by Django 4.1.6 on 2023-02-08 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UNGoals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('COMP', 'Competition'), ('LOOSE', 'Loosely Defined'), ('WELLDF', 'Well Defined'), ('C4', 'C4')], max_length=6)),
                ('source', models.CharField(max_length=30, null=True)),
                ('students', models.CharField(blank=True, default=None, max_length=120)),
                ('supervisor', models.CharField(blank=True, default=None, max_length=60)),
                ('date_proposed', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('PROP', 'Proposed / Unstarted'), ('START', 'Started / In Progress'), ('COMPL', 'Completed'), ('EXT', 'Completed / Extendable')], default='PROP', max_length=30)),
                ('date_complete', models.DateField(blank=True, default=None, null=True)),
                ('industry_partners', models.CharField(blank=True, default=None, max_length=60)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, default=None)),
                ('discipline', models.ManyToManyField(to='projects.engdiscipline')),
                ('un_goals', models.ManyToManyField(blank=True, default=None, to='projects.ungoals')),
            ],
        ),
    ]
