# Generated by Django 4.1.6 on 2023-03-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='temp',
        ),
    ]
