# Generated by Django 4.1.6 on 2023-04-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('PROF', 'Professor'), ('TA', 'Teaching Assistant'), ('OTHER', 'Other Staff')], default='PROF', max_length=5)),
                ('department', models.CharField(choices=[('OTHR', 'Other'), ('AMPD', 'School of the Arts, Media, Performance & Design'), ('ED', 'Faculty of Education'), ('FEUC', 'Faculty of Environmental & Urban Change'), ('GL', 'Glendon College'), ('FGS', 'Faculty of Graduate Studies'), ('FH', 'Faculty of Health'), ('LSE', 'Lassonde School of Engineering'), ('CIVL', 'Civil Engineering'), ('ESSE', 'Earth and Space Science and Engineering'), ('EECS', 'Electrical Engineering & Computer Science'), ('MECH', 'Mechanical Engineering'), ('LAPS', 'Faculty of Liberal Arts & Professional Studies'), ('OH', 'Osgoode Hall Law School'), ('SSB', 'Schulich School of Business'), ('SC', 'Faculty of Science')], default='OTHR', max_length=4)),
                ('fields_of_interest', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
