# Generated by Django 4.1.5 on 2023-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capstone', models.IntegerField(default=2022)),
                ('title', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Capstone',
            fields=[
                ('starting_year', models.IntegerField(default=2023, primary_key=True, serialize=False)),
                ('capstone_day', models.DateField(blank=True, default=None, null=True)),
                ('capstone_day_location', models.CharField(blank=True, default=None, max_length=100)),
                ('capstone_day_judges', models.CharField(blank=True, default=None, max_length=200)),
                ('teaching_notes', models.TextField(blank=True, default=None)),
                ('other_notes', models.TextField(blank=True, default=None)),
                ('teaching_assistants', models.ManyToManyField(blank=True, default=None, related_name='ta_list', to='faculty.faculty')),
                ('teaching_staff', models.ManyToManyField(blank=True, default=None, related_name='staff_list', to='faculty.faculty')),
            ],
        ),
    ]
